#!/bin/bash
set -e

build_site() {
  mkdir -p work
  rm -rf "work/$1"
  mkdir -p "work/$1"
  cp -r template/site "work/$1"
  cp "sites/$1/docusaurus.config.js" "work/$1/site"
  mkdir -p "sites/$1/blog"
  mkdir -p "sites/$1/docs"
  (
    cd "sites/$1/blog"
    echo "INFO: Adding blog entries for $1"
    cp * "../../../../work/$1/site/blog" || true
    cd "../docs"
    echo "INFO: Adding docs for $1"
    cp * "../../../../work/$1/site/docs" || true
    cp ../../../../www/docs/* "../../../../work/$1/site/docs"
  )
  "work/$1/site/s3d-apply" "s3://$2"
}

build_site nc/apex apex-nc-k9sit-com-camel-230303
build_site nc/durham durham-nc-k9sit-com-osprey-230303
build_site nc/chapel-hill chapel-hill-nc-k9sit-com-polecat-230303
build_site nc/raleigh-ne ne-raleigh-nc-k9sit-com-llama-230222
build_site nc/raleigh-nw nw-raleigh-nc-k9sit-com-jackass-230302
build_site nc/raleigh-se se-raleigh-nc-k9sit-com-termite-230302
build_site nc/raleigh-sw sw-raleigh-nc-k9sit-com-loon-230302
build_site nc/wake-forest wake-forest-k9sit-com-shrimp-230302

# rm -rf work

www/s3d-apply
