#!/bin/bash
set -e

build_site() {
  mkdir -p work
  rm -rf "work/$1"
  mkdir -p "work/$1"
  cp -r template/site "work/$1"

  cp "sites/$1/docusaurus.config.js" "work/$1/site"

  if [ -e "sites/$1/components/HomepageFeatures/index.js" ]; then
    cp "sites/$1/components/HomepageFeatures/index.js" "work/$1/site/src/components/HomepageFeatures/index.js"
  fi

  mkdir -p "sites/$1/blog"
  mkdir -p "sites/$1/docs"
  mkdir -p "sites/$1/static/img"
  (
    cd "sites/$1/blog"
    echo "INFO: Adding blog entries for $1"
    cp * "../../../../work/$1/site/blog" || true
    cd "../docs"
    echo "INFO: Adding docs for $1"
    cp ../../../../www/docs/* "../../../../work/$1/site/docs"
    cp * "../../../../work/$1/site/docs" || true
    cd "../static/img"
    echo "INFO: Adding images for $1"
    pwd
    cp ../../../../../www/static/img/* "../../../../../work/$1/site/static/img"
  )
  "work/$1/site/s3d-apply" "s3://$2"
}

build_site fl/daytona-beach daytona-beach-fl-k9sit-com-seagull-230328
build_site oh/kent kent-oh-k9sit-com-buffalo-230329
build_site nc/raleigh-ne ne-raleigh-nc-k9sit-com-llama-230222

www/s3d-apply
rm -rf work
