#!/bin/bash
set -e

# Switch to script directory
cd "$(dirname "$0")"

# Build (with npm install if needed)
npm run build

aws s3 sync --delete build "s3://$(cd ..; terraform output -json  root_site | jq -r '.[0].s3_bucket')"
aws s3 sync --delete build "s3://$(cd ..; terraform output -json  sites | jq -r '.www[0].s3_bucket')"
