#!/bin/bash
set -e

# Switch to script directory
cd "$(dirname "$0")"

# Build (with npm install if needed)
npm run build

aws s3 sync --delete build 's3://www-k9sit-com-jackass-230213'
aws s3 sync --delete build 's3://k9sit-com-parrot-230219'
