#!/bin/bash
set -e

# Switch to script directory
cd "$(dirname "$0")"

# Build (with npm install if needed)
npm run build

aws s3 sync --delete build 's3://www-k9sit-com-gibbon-241101'
aws s3 sync --delete build 's3://k9sit-com-jay-241101'
