#!/bin/bash
set -e

# Switch to script directory
cd "$(dirname "$0")"

# Build (with npm install if needed)
npm i @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/module-type-aliases@latest
npm run build

aws s3 sync --delete build 's3://k9me-com-macaque-230428'
aws s3 sync --delete build 's3://www-k9me-com-hornet-230428'
